In [1]:
import numpy as np
import pandas as pd
import os
os.getcwd()

'C:\\Users\\KUMAR SUNDRAM\\Desktop\\Adv AI - 1st June 2024\\DNN'

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [3]:
dataset = dataset.iloc[:,2:]
dataset.head()

Age  EstimatedSalary  Purchased
0  19.0          19000.0          0
1  35.0          20000.0          0
2  26.0          43000.0          0
3  27.0          57000.0          0
4  19.0          76000.0          0

In [4]:
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [5]:
x.head()

Age  EstimatedSalary
0  19.0          19000.0
1  35.0          20000.0
2  26.0          43000.0
3  27.0          57000.0
4  19.0          76000.0

In [6]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [8]:
# Data Normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaler = scaler.fit_transform(x)
pd.DataFrame(x_scaler)

0         1
0   -1.781797 -1.490046
1   -0.253587 -1.460681
2   -1.113206 -0.785290
3   -1.017692 -0.374182
4   -1.781797  0.183751
..        ...       ...
395  0.797057 -0.844019
396  1.274623 -1.372587
397  1.179110 -1.460681
398 -0.158074 -1.078938
399  1.083596 -0.990844

[400 rows x 2 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaler, y, test_size=0.2, random_state=42, stratify=y)

In [9]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Dropout
from keras import Sequential

In [11]:
# Vanishing Gradient problem occurs
model = Sequential()
model.add(Dense(128, activation='sigmoid', input_dim=2))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

C:\Users\KUMAR SUNDRAM\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - accuracy: 0.5521 - loss: 0.6845 - val_accuracy: 0.6375 - val_loss: 0.6624
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6261 - loss: 0.6679 - val_accuracy: 0.6375 - val_loss: 0.6599
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6359 - loss: 0.6558 - val_accuracy: 0.6375 - val_loss: 0.6665
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6807 - loss: 0.6231 - val_accuracy: 0.6375 - val_loss: 0.6587
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6443 - loss: 0.6569 - val_accuracy: 0.6375 - val_loss: 0.6550
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6449 - loss: 0.6531 - val_accuracy: 0.6375 - val_loss: 0.6568
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6580 - loss: 0.6430 - val_accuracy: 0.6375 - val_loss: 0.6552
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6248 - loss: 0.6629 - val_accuracy: 0.

In [13]:
# How to solve the problem
## point 1) reduce the complexity
## point 2 ) In hidden layer, use Relu activation function
# Vanishing Gradient problem occurs
model1 = Sequential()
model1.add(Dense(128, activation='relu', input_dim=2))
model1.add(Dense(128, activation='relu'))
model1.add(Dense(1, activation='sigmoid'))

model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model1.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.7316 - loss: 0.6668 - val_accuracy: 0.8000 - val_loss: 0.5848
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8563 - loss: 0.5181 - val_accuracy: 0.8000 - val_loss: 0.4951
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8645 - loss: 0.4124 - val_accuracy: 0.8125 - val_loss: 0.4299
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8748 - loss: 0.3436 - val_accuracy: 0.8250 - val_loss: 0.3798
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8768 - loss: 0.3147 - val_accuracy: 0.8875 - val_loss: 0.3417
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9031 - loss: 0.2774 - val_accuracy: 0.8750 - val_loss: 0.3159
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8958 - loss: 0.2839 - val_accuracy: 0.8875 - val_loss: 0.2955
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9036 - loss: 0.2595 - val_accuracy: 0.8875

In [14]:
# using dropout

model2 = Sequential()
model2.add(Dense(128, activation='relu', input_dim=2))
model2.add(Dropout(0.5))
model2.add(Dense(128, activation='relu'))
model2.add(Dropout(0.5))
model2.add(Dense(1, activation='sigmoid'))

model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model2.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5661 - loss: 0.6727 - val_accuracy: 0.8125 - val_loss: 0.6015
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8114 - loss: 0.5585 - val_accuracy: 0.8000 - val_loss: 0.5253
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8596 - loss: 0.4696 - val_accuracy: 0.8125 - val_loss: 0.4650
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8099 - loss: 0.4345 - val_accuracy: 0.8000 - val_loss: 0.4157
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8705 - loss: 0.3500 - val_accuracy: 0.8000 - val_loss: 0.3774
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8509 - loss: 0.3505 - val_accuracy: 0.8250 - val_loss: 0.3508
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8624 - loss: 0.3408 - val_accuracy: 0.8750 - val_loss: 0.3315
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8699 - loss: 0.3189 - val_accuracy: 0.8875 - 

In [16]:
from keras.layers import BatchNormalization

In [18]:
model3 = Sequential()
model3.add(Dense(64, activation='relu', input_dim=2))
model3.add(Dropout(0.5))
#model3.add(BatchNormalization())
model3.add(Dense(64, activation='relu'))
model3.add(Dropout(0.5))
#model3.add(BatchNormalization())
model3.add(Dense(1, activation='sigmoid'))

model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model3.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=50)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.4244 - loss: 0.7193 - val_accuracy: 0.8375 - val_loss: 0.6565
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6703 - loss: 0.6470 - val_accuracy: 0.8250 - val_loss: 0.6068
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8071 - loss: 0.5769 - val_accuracy: 0.8125 - val_loss: 0.5629
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8499 - loss: 0.5311 - val_accuracy: 0.8125 - val_loss: 0.5225
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8483 - loss: 0.4912 - val_accuracy: 0.8250 - val_loss: 0.4837
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8500 - loss: 0.4395 - val_accuracy: 0.8250 - val_loss: 0.4474
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.4361 - val_accuracy: 0.8125 - val_loss: 0.4195
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8643 - loss: 0.3933 - val_accuracy: 0.8375 - val_los

# Pytorch 

In [19]:
!pip install torch

In [20]:
# import the torch library followed by torch.nn library as nn
import torch
import torch.nn as nn

In [21]:
# Assign inputs to the neuron
# Inputs to the neuron - we have used random values here
inputs = torch.tensor([3.0,2.0, -1.0])
inputs

tensor([ 3.,  2., -1.])

In [22]:
# create a neuron with 3 features and 1 output
neuron = nn.Linear(in_features = 3, out_features=1)
output = neuron(inputs)

In [23]:
output

tensor([1.5647], grad_fn=<ViewBackward0>)

In [24]:
print(neuron.weight)

Parameter containing:
tensor([[ 0.4175,  0.1426, -0.1370]], requires_grad=True)


In [25]:
print(neuron.bias)

Parameter containing:
tensor([-0.1100], requires_grad=True)


In [27]:
# Formula for the final output of the neuron
neuron.weight@inputs.T + neuron.bias

C:\Users\KUMAR SUNDRAM\AppData\Local\Temp\ipykernel_17740\1648406665.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3679.)
  neuron.weight@inputs.T + neuron.bias


tensor([1.5647], grad_fn=<AddBackward0>)

In [30]:
# Prodigy_University_Dataset dataset - using Pytorch/torch library
import os
os.getcwd()

'C:\\Users\\KUMAR SUNDRAM\\Desktop\\Adv AI - 1st June 2024\\DNN'

In [ ]:
Prodigy University Dataset

In [31]:
import pandas as pd
data = pd.read_csv('Prodigy University Dataset.csv')
data.head()

sat_sum  hs_gpa  fy_gpa
0      508    3.40    3.18
1      488    4.00    3.33
2      464    3.75    3.25
3      380    3.75    2.42
4      428    4.00    2.63

In [32]:
x = data[['sat_sum', 'hs_gpa']].values
y = data['fy_gpa'].values.reshape(-1,1)

In [33]:
x.shape

(1000, 2)

In [34]:
y.shape

(1000, 1)

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [37]:
x_train

array([[-1.61475533,  0.58852578],
       [-1.40573678,  0.40195133],
       [-0.43031692, -0.90406983],
       ...,
       [ 1.79921419,  1.52139804],
       [-1.68442817, -0.53092092],
       [ 0.26641155,  0.40195133]])

In [38]:
import torch
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [39]:
import torch.nn as nn

In [40]:
# Building the MLP model
model = nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)   
)

In [50]:
import torch.nn.functional as F

In [54]:
"""
# Building the MLP model
model = nn.Sequential(
    nn.Linear(2,128),
    nn.ReLU(),
    nn.Linear(128),
    nn.ReLU(),
    nn.Linear(128,5)  
    nn.Softmax()
)"""

In [41]:
# forward propagation
preds_train = model(x_train_tensor)
preds_test = model(x_test_tensor)
print(preds_train)

tensor([[0.5041],
        [0.5133],
        [0.6015],
        [0.4740],
        [0.6337],
        [0.4389],
        [0.3605],
        [0.3764],
        [0.7173],
        [0.4114],
        [0.3801],
        [0.5060],
        [0.5620],
        [0.6005],
        [0.6918],
        [0.5690],
        [0.3991],
        [0.3722],
        [0.6279],
        [0.7251],
        [0.6128],
        [0.4264],
        [0.4156],
        [0.5446],
        [0.4477],
        [0.3744],
        [0.7179],
        [0.6131],
        [0.5160],
        [0.5182],
        [0.5649],
        [0.5248],
        [0.5126],
        [0.4815],
        [0.3372],
        [0.3412],
        [0.4114],
        [0.5366],
        [0.3391],
        [0.5759],
        [0.4236],
        [0.7210],
        [0.4415],
        [0.4872],
        [0.6356],
        [0.4483],
        [0.6823],
        [0.3990],
        [0.3429],
        [0.3967],
        [0.4261],
        [0.3007],
        [0.4550],
        [0.6641],
        [0.5779],
        [0

In [42]:
print(preds_test)

tensor([[0.5346],
        [0.6309],
        [0.6624],
        [0.4118],
        [0.5280],
        [0.5045],
        [0.4518],
        [0.6707],
        [0.4452],
        [0.3989],
        [0.7343],
        [0.6602],
        [0.4945],
        [0.5015],
        [0.5917],
        [0.3754],
        [0.6835],
        [0.5856],
        [0.3879],
        [0.4916],
        [0.4471],
        [0.6614],
        [0.4951],
        [0.4056],
        [0.3823],
        [0.5456],
        [0.5334],
        [0.4622],
        [0.4545],
        [0.5855],
        [0.4909],
        [0.3161],
        [0.4743],
        [0.6393],
        [0.4093],
        [0.7656],
        [0.6396],
        [0.5975],
        [0.4997],
        [0.4957],
        [0.6950],
        [0.3385],
        [0.6162],
        [0.6458],
        [0.4945],
        [0.4912],
        [0.3569],
        [0.4105],
        [0.5669],
        [0.3887],
        [0.5562],
        [0.7442],
        [0.3233],
        [0.6511],
        [0.4452],
        [0

In [44]:
from torch.nn import MSELoss

In [45]:
criterion = MSELoss()
loss1 = criterion(preds_train, y_train_tensor)
loss2 = criterion(preds_test, y_test_tensor)
print(loss1)
print()
print(loss2)

tensor(4.4771, grad_fn=<MseLossBackward0>)

tensor(4.7050, grad_fn=<MseLossBackward0>)


In [46]:
model[0].weight

Parameter containing:
tensor([[-0.2165, -0.6344],
        [-0.2220, -0.2484]], requires_grad=True)

In [48]:
model[2].weight

Parameter containing:
tensor([[0.5388, 0.2492]], requires_grad=True)